### ISSUE TITLE
Update the API documentation on the new fields

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse-annotator#206]
With respect to earlier versions of OE, there are several new fields in annotations and codes. As a result, our documentation has become obsolete. I have written an (updated) question [on the Edgeryders platform](https://edgeryders.eu/t/using-the-edgeryders-eu-apis/7904/4?u=alberto). Happy to take care of the update myself, but some fields I need an explanation for. @tanius or @damingo will know this.

**Comment by albertocottica** [comment]
Hello, I noticed that this was never answered @damingo .

**Comment by damingo** [comment]
I added some annotations to the [API example](https://edgeryders.eu/t/using-the-edgeryders-eu-apis/7904#h3-idheading-3-232-ethnographic-annotationsh3-9). The JSON API takes all the attributes present in the annotation table. Some of them will probably never be needed in the API, but we've kept them because we don't know for sure.

**Comment by albertocottica** [comment]
Thanks for this!
