### ISSUE TITLE
Prettify and enhance the list view for codes (exporting the codebook of a project)

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse-annotator#231]
The codebook of an ethnographic project is a list of the codes used in that project. Open Ethnographer has partial support for this in the list view:  https://edgeryders.eu/annotator/codes?discourse_tag=ethno-icqe2022&view=list.

However, this is still pretty ugly and does not contain all relevant informations. For example, the translations of the labels (when present) and the number of annotations each code has are useful informations to have. 

Can it be improved? The ultimate goal is to copy-paste in a word processor for making reports and such.

**Comment by tanius** [comment]
After playing around with Google Docs and Google Sheets a bit (as these would be our report writing tools), here is my proposal: there should be a new mode "View: Plain Table", in analogy to the existing "View: Plain List" mode now. This is because this new mode will be something experimental and should not destroy the exiting plain list mode. (We may however remove the plain list mode later in case the plain table mode turns out to be successful.)

This "Plain Table" mode should show all codes matching the filter criteria in a table that is optimized for being copy&pasted to Google Sheets. It can also be copy&pasted to Google Docs directly, but the route via Google Sheets will be better in practice as that allows to make bulk modifications such as moving parts, deleting hierarchy layers that are only there for internal reasons etc..

The table should have a single row with column titles at the top. Google Docs now has a "pin header" function for tables that allows to automatically repeat this title row when the table is spread over several pages. So a very long table with just one title row is fine.

The column structure of this table should be as follows, from left to right:

**(1) Name, description, hierarchy.** Several columns that are used for both the code name, code description and for an indentation indicating the hierarchy level. This should use the space-saving "**Code name.** Description." formatting as currently used in the "Plain List" view, plus one empty column for each hierarchy level indentation, resp. rowspans for codes that are on higher hierarchy levels and should not be indented. Example with just one indentation level:

<table>
<thead>
  <tr>
    <td colspan="2"><b>Level 1 code.</b> Description.</td>
    <td>other column</td>
  </tr>
</thead>
<tbody>
  <tr>
    <td></td>
    <td><b>Level 2 code.</b> Description.</td>
    <td>other column</td>
  </tr>
</tbody>
</table>

**(2) Other code names.** The first text column would contain the code name in English, or if not available in the code's original language. Any translated code names should be filled into this next column, prefixed with the language codes. Example for a German code translation: "de: sozialer Wandel". Probably use one code name per line, and format the language labels in bold, so "**de:** sozialer Wandel".

**(3) Annotations.** A column containing the number of annotations that a code has. Ideally again using the scheme from the default tree view of codes where both the count of parent code annotations and the count of descendant code annotations is shown, for example "5 + 32".

**(4) Code author.** The username of the code's creator. Probably not needed in reports, but it's simple enough then to remove this column after copying to Google Sheets, Google Docs or a similar tool.

Please let me know if anyone has better ideas for the formatting. The above is the best I could come up with, even though long tables inside Google Docs are a bit of a pain. In practice, one would often create 10-20 or more sub-chapters in a Google Docs document, one each for the first level of codes, esp. where codes have been used for structure rather than semantics. For example, the "Z Actions and Activities - Category" code of the POPREBEL project is a good example. It would become a chapter, which is a more appropriate item to represent it in the codebook than using an actual code.

**Comment by albertocottica** [comment]
> Please let me know if anyone has better ideas for the formatting. 

I think it is difficult to create a tidy layout that does *both* the job of making a list of codes *and* the entirely different job of representing their hierarchy. I would focus on the first one: no empty column, just a column with the English label of the parent code. 

We should represent the hierarchy (if needed, not all projects have it) separately. A way to do it is to use Tulip's tree layout algorithms. If there is a simple way to output it in HTML, that would be a win, but if not I think this is not a priority for now.

**Comment by tanius** [comment]
> no empty column, just a column with the English label of the parent code

Ok, I discussed with Daniel that we'll follow that proposal then. Makes things simpler as well. We'll place the parent column second and include the full path there for context, not just the immediate parent code.

**Comment by damingo** [comment]
> Can we do one better, and include the path in a way that makes a spreadsheet sortable on that column in a way that makes intuitive sense?

Sorting the path column alphabetically will sort codes by depth like: 
A 
A > B
A > B > C

Does that work, or what kind of sorting do you have in mind?

**Comment by albertocottica** [comment]
> Sorting the path column alphabetically will sort codes by depth

Aha. So:

```
apples 
apples => austrian apples
addresses = zimbabwean apples
bees
bees => angry bees
bees => angry bees => really angry bees
bees => blissful bees
```

Yes, that kind of works!

**Comment by tanius** [comment]
> Sorting the path column alphabetically will sort codes by depth

When the path is a single string with some sort of hierarchy separator character ("apples → austrian apples"), then I don't think that sorting would work as desired. The hierarchy separator character and space characters would most likely be ignored for sorting purposes, so we'd get this sort order:

```
apples
applesauce
apples → austrian apples
```

while we'd want this: 

```
apples
apples → austrian apples
applesauce
```

It would only work when having one column per hierarchy level of the path, as then one can define grouped sorting in the spreadsheet, using multiple sort keys. As in: sort by first path element, and for those that have identical values there sort them by second path element, and so on.

If that is desired, then I propose including _both_ the full path in one column, and as the last columns also this set of columns with one column per path element. The first is for presentation purposes in the report ("compact and beautiful"), while the second is only for working with the table in a spreadsheet and would not be taken over into the report.

**Comment by albertocottica** [comment]
You are right of course @tanius. I like that a lot. 

Which reminds me, we have a lot of documentation to write. Let's get together at some point and see if we can get some ideas.

**Comment by damingo** [comment]
Tested sorting in Google Sheets. The example given by @tanius is properly sorted as:

```
apples
apples → austrian apples
applesauce
```
So we don't need the extra columns?

**Comment by albertocottica** [comment]
So the space comes before any letter or sign? I did not know, should have tested it. Seems like, indeed, we don't need the extra columns.

**Comment by damingo** [comment]
Uploaded a new version were "View: Plain Table" can be selected. 

As discussed with @tanius we added two more columns `Descendant codes` and `Annotations of descendant codes` to allow doing some sorting and math in a spreadsheet, if desired.

Anything missing @albertocottica ?

**Comment by albertocottica** [comment]
Looks good, thanks! Let's have a meeting on how to update/keep documentation.

**Comment by tanius** [comment]
Thanks, Daniel. Closing this as completed :)

Please open a new issue if any bug is encountered with this new feature.
